version: '3'
services: 
    db:
        image: 'mongo'
        container_name: 'mongo'
        environment: 
            - MONGO_INITDB_DATABASE=meals-local
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=pass
        ports:
            - '27017-27019:27017-27019'
    api:
        build: ./backend
        ports:
            - '8080:8080'
        environment:
            - MONGO_HOST=db
            - MONGO_PORT=27017
            - MONGO_USERNAME=user
            - MONGO_PASSWORD=pass
            - APP_FIREBASE_KEY_FILE=app-key.json
        volumes: 
            - ./backend/app-key.json:/dist/app-key.json
        depends_on: 
            - db
    web:
        build : ./frontend
        ports:
            - '80:80'
        depends_on: 
            - api
